# Generated by Django 4.2.4 on 2023-08-22 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_provider_phone_number'),
        ('prihods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prihod',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Поставшики', to='storage.provider'),
        ),
    ]
