# Generated by Django 4.2.4 on 2023-08-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='Phone_number',
            field=models.IntegerField(),
        ),
    ]
