# Generated by Django 4.2.4 on 2023-08-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryname',
            field=models.CharField(blank=True, default='category_default', max_length=100, null=True, verbose_name='Категория'),
        ),
    ]
