# Generated by Django 4.2.4 on 2023-08-11 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prodaja', '0003_prodaja_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodajadetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(verbose_name='Размер')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('price', models.FloatField(max_length=100, verbose_name='Цена')),
                ('prihod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodaja', to='prodaja.prodaja')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
            },
        ),
    ]
