# Generated by Django 4.2.4 on 2023-08-11 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produkts', '0001_initial'),
        ('prodajadetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodajadetail',
            name='produktname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Название', to='produkts.produkt'),
            preserve_default=False,
        ),
    ]
