# Generated by Django 4.2.4 on 2023-08-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodajadetails', '0002_prodajadetail_produktname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodajadetail',
            name='produktname',
        ),
    ]
