# Generated by Django 4.2.4 on 2023-08-11 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produkts', '0002_produkt_category_alter_produkt_produktname'),
        ('prodajadetails', '0003_remove_prodajadetail_produktname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodajadetail',
            old_name='prihod',
            new_name='prodaja',
        ),
        migrations.AddField(
            model_name='prodajadetail',
            name='produktname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Название', to='produkts.produkt'),
        ),
    ]
