# Generated by Django 4.2.4 on 2023-08-10 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_password'),
        ('prodaja', '0002_rename_agent_prodaja_agentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodaja',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.user'),
            preserve_default=False,
        ),
    ]
