# Generated by Django 4.2.4 on 2023-08-11 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0002_alter_provider_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produktname', models.CharField(max_length=100, verbose_name='Наименование')),
                ('size', models.IntegerField(verbose_name='Размер')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('price', models.FloatField(max_length=100, verbose_name='Цена')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Провайдер', to='storage.provider')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
