# Generated by Django 4.2.4 on 2023-08-11 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0002_alter_category_categoryname'),
        ('produkts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Котегори', to='categorys.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produkt',
            name='produktname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование'),
        ),
    ]
