# Generated by Django 4.2.4 on 2023-08-11 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prihods', '0001_initial'),
        ('produkts', '0002_produkt_category_alter_produkt_produktname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prihoddetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(verbose_name='Размер')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('price', models.FloatField(max_length=100, verbose_name='Цена')),
                ('prihod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Деталиприхода', to='prihods.prihod')),
                ('produktname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='НазваниеПродукта', to='produkts.produkt')),
            ],
            options={
                'verbose_name': 'ПриходДеталь',
                'verbose_name_plural': 'ПриходДетали',
            },
        ),
    ]
