# Generated by Django 4.2.4 on 2023-08-12 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prihoddetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prihoddetail',
            options={'verbose_name': 'ПриходДеталь', 'verbose_name_plural': 'ДеталиПрихода'},
        ),
    ]
